# Generated by Django 4.0.3 on 2022-03-13 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_alter_category_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categories',
        ),
    ]
